import '../models/vault_category.dart';
import '../services/supabase_database_service.dart';

/// Repository for managing user-created categories.
/// Strict rule: No default categories. Every category is user-created.
class CategoryRepository {
  final SupabaseDatabaseService databaseService;

  CategoryRepository({required this.databaseService});

  Future<List<VaultCategory>> getCategories(String userId) {
    return databaseService.getCategories(userId);
  }

  Future<VaultCategory> createCategory({
    required String userId,
    required String name,
    required int colorValue,
  }) {
    final now = DateTime.now();
    final category = VaultCategory(
      id: '', // Generated by Supabase default gen_random_uuid()
      userId: userId,
      name: name.trim(),
      colorValue: colorValue,
      createdAt: now,
      updatedAt: now,
    );
    return databaseService.createCategory(category);
  }

  Future<void> updateCategory(VaultCategory category) {
    return databaseService.updateCategory(category);
  }

  Future<void> deleteCategory(String categoryId, String userId) {
    return databaseService.deleteCategoryWithPhotos(categoryId, userId);
  }

  Future<void> setCoverPhoto(
    String categoryId,
    String userId,
    String photoId,
  ) async {
    final categories = await databaseService.getCategories(userId);
    final target = categories.firstWhere((c) => c.id == categoryId);
    final updated = target.copyWith(
      coverPhotoId: photoId,
      updatedAt: DateTime.now(),
    );
    await databaseService.updateCategory(updated);
  }
}
